build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Cedric Bach - Developer"
    email: "cedric@eazybank.com"
  onCallSupport:
    - (453) 895-7452
    - (943) 865-7412
