spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Serena Anderson - Product Owner"
    email: "serena@eazybank.com"
  onCallSupport:
    - (987) 654-3214
    - (874) 564-4587