spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Deren Massimo - QA Lead"
    email: "deren@eazybank.com"
  onCallSupport:
    - (564) 897-4532
    - (153) 654-7823