services:
  accounts:
    image: "ezgicagla0/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ezgicagla0
  loans:
    image: "ezgicagla0/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ezgicagla0
  cards:
    image: "ezgicagla0/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ezgicagla0
networks:
  ezgicagla0:
    driver: "bridge"